theme: minima
title: Bio AI – All things brain
author: Katarzyna (Kasia) Kożdoń
description: Bookmark this to keep an eye on my project updates!
url: 'https://kasiakozdon.github.io/'

header_pages:
  - about.md
